use vk;

SHOW TABLES;
SELECT * FROM users LIMIT 10;

UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE created_at > updated_at 

SELECT * FROM profiles LIMIT 10;

ALTER TABLE profiles ADD COLUMN photo_id INT UNSIGNED;
SELECT * FROM messages LIMIT 10;
SELECT COUNT(*) FROM users;
SELECT FLOOR(0 + RAND()*2); 
# отсутствуют данные gender
UPDATE profiles SET gender = FLOOR(1 + RAND()*2);
UPDATE profiles SET gender = 'f' WHERE gender = 2;
UPDATE profiles SET gender = 'm' WHERE gender != 'f';
# отсутствуют данные country
UPDATE profiles SET photo_id = FLOOR(1 + RAND()*10);
UPDATE profiles SET country = 'United Kingdom' WHERE photo_id = 1;
UPDATE profiles SET	country = 'USA' WHERE photo_id = 2;
UPDATE profiles SET	country = 'Spain' WHERE photo_id = 3;
UPDATE profiles SET	country = 'Ausria' WHERE photo_id = 4;
UPDATE profiles SET	country = 'Italy' WHERE photo_id = 5;
UPDATE profiles SET	country = 'New Zealand' WHERE photo_id = 6;
UPDATE profiles SET country = 'China' WHERE photo_id = 7;
UPDATE profiles SET	country = 'Israel' WHERE photo_id = 8;
UPDATE profiles SET	country = 'Canada' WHERE photo_id = 9;
UPDATE profiles SET	country = 'Singapore' WHERE photo_id = 10;
UPDATE profiles SET photo_id = FLOOR(1 + RAND()*200);

SELECT * FROM messages LIMIT 10;
UPDATE messages SET
	from_user_id = FLOOR(1 + RAND()*200),
	to_user_id = FLOOR(1 + RAND()*200);
SELECT * FROM messages WHERE from_user_id = to_user_id;

DESC media;
SELECT * FROM media_types;
DELETE FROM media_types;
INSERT INTO media_types (name) VALUES
	('photo'),
	('video'),
	('audio');
TRUNCATE media_types;

SELECT * FROM media LIMIT 100;
UPDATE media SET media_type_id = FLOOR(1 + RAND()*3);
UPDATE media SET user_id = FLOOR(1 + RAND()*100);
UPDATE media SET filename = CONCAT('https://dropbox.com/vk/',filename); 
CREATE TEMPORARY TABLE exts (name VARCHAR (10));
INSERT INTO exts VALUES ('gif'), ('avi'), ('jpeg');
SELECT * FROM exts;
SELECT name FROM exts ORDER BY RAND () LIMIT 1;
UPDATE media SET filename = CONCAT(filename,'.',(SELECT name FROM exts ORDER BY RAND () LIMIT 1));
UPDATE media SET `size` = FLOOR(10000 + RAND()*10000) WHERE `size` < 5000;
UPDATE media SET metadata = CONCAT('{"owner":"',
	(SELECT CONCAT(first_name, '', last_name) FROM users WHERE id = user_id),
	'"}');
ALTER TABLE media MODIFY COLUMN metadata JSON;


SELECT * FROM friendship LIMIT 10;
UPDATE friendship SET
	user_id = FLOOR(1 + RAND()*200),
	friend_id = FLOOR(1 + RAND()*200);

SELECT * FROM friendship_statuses;
TRUNCATE friendship_statuses;
INSERT INTO friendship_statuses (name) VALUES
	('Requested'),
	('Confermed'),
	('Rejected');

UPDATE friendship SET status_id = FLOOR(1 + RAND()*3);

SELECT * FROM communities;
DELETE FROM communities WHERE id > 20;

SELECT * FROM communities_users;
UPDATE communities_users SET 
	community_id = FLOOR(1 + RAND()*20),
	user_id = FLOOR(1 + RAND()*100);

SHOW TABLES;
DESC messages;
SELECT * FROM media LIMIT 10;

#---body не заполнена, взял данные из filldb.dump.sql------

DELETE FROM messages;
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (1, 1, 1, 1, 'Footman\'s head: it just grazed his nose, you know?\' \'It\'s the stupidest tea-party I ever saw one that size? Why, it fills the whole court was in the last time she saw in another moment it was the.', 1, 1, '2018-03-31 23:10:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (2, 2, 2, 2, 'I ever saw one that size? Why, it fills the whole party at once to eat some of them bowed low. \'Would you tell me,\' said Alice, in a sort of way, \'Do cats eat bats?\' and sometimes, \'Do bats eat.', 0, 1, '2010-11-06 04:01:11');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (3, 3, 3, 3, 'By the time at the Hatter, and he went on eagerly. \'That\'s enough about lessons,\' the Gryphon in an offended tone, \'so I should be free of them even when they met in the last time she heard it.', 0, 0, '2017-01-07 14:22:08');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (4, 4, 4, 4, 'Imagine her surprise, when the Rabbit began. Alice gave a look askance-- Said he thanked the whiting kindly, but he now hastily began again, using the ink, that was said, and went on for some time.', 0, 0, '2019-12-11 12:16:33');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (5, 5, 5, 5, 'And yet I wish I hadn\'t to bring tears into her face, with such a pleasant temper, and thought to herself. At this moment the King, \'or I\'ll have you executed on the shingle--will you come and join.', 1, 0, '2019-11-13 17:05:26');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (6, 6, 6, 6, 'White Rabbit read:-- \'They told me he was going to begin at HIS time of life. The King\'s argument was, that anything that had a door leading right into a butterfly, I should be free of them didn\'t.', 0, 0, '2017-05-09 14:16:31');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (7, 7, 7, 7, 'So she stood looking at everything that Alice said; but was dreadfully puzzled by the little door, so she tried the effect of lying down with wonder at the time he was in such confusion that she was.', 0, 0, '2017-10-26 00:26:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (8, 8, 8, 8, 'Alice panted as she could, and waited to see if she was exactly three inches high). \'But I\'m not Ada,\' she said, without opening its eyes, for it now, I suppose, by being drowned in my own tears!.', 1, 0, '2016-06-01 14:31:48');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (9, 9, 9, 9, 'And she squeezed herself up closer to Alice\'s side as she swam lazily about in the house opened, and a Canary called out as loud as she heard a little nervous about this; \'for it might happen any.', 1, 1, '2012-09-26 02:51:50');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (10, 10, 10, 10, 'I suppose Dinah\'ll be sending me on messages next!\' And she tried to fancy to cats if you were all shaped like ears and whiskers, how late it\'s getting!\' She was walking hand in hand, in couples:.', 1, 1, '2016-02-03 06:05:36');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (11, 11, 11, 11, 'King and the White Rabbit interrupted: \'UNimportant, your Majesty means, of course,\' said the March Hare. \'It was much pleasanter at home,\' thought poor Alice, \'to speak to this last remark that had.', 1, 1, '2019-06-17 09:27:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (12, 12, 12, 12, 'I wonder?\' Alice guessed in a soothing tone: \'don\'t be angry about it. And yet I wish you wouldn\'t squeeze so.\' said the Cat: \'we\'re all mad here. I\'m mad. You\'re mad.\' \'How do you know I\'m mad?\'.', 0, 1, '2016-10-06 05:11:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (13, 13, 13, 13, 'Alice was only sobbing,\' she thought, and it was very nearly getting up and down, and was going a journey, I should think very likely true.) Down, down, down. There was exactly one a-piece all.', 0, 1, '2019-02-18 19:35:03');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (14, 14, 14, 14, 'CHAPTER IX. The Mock Turtle sang this, very slowly and sadly:-- \'\"Will you walk a little faster?\" said a whiting to a shriek, \'and just as well as she could not taste theirs, and the three gardeners.', 1, 0, '2017-12-15 19:58:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (15, 15, 15, 15, 'ME,\' said Alice very politely; but she remembered how small she was going to begin lessons: you\'d only have to whisper a hint to Time, and round the court with a large ring, with the next witness..', 1, 0, '2013-12-13 19:35:09');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (16, 16, 16, 16, 'Mabel after all, and I had our Dinah here, I know who I WAS when I grow up, I\'ll write one--but I\'m grown up now,\' she said, \'and see whether it\'s marked \"poison\" or not\'; for she thought, \'and hand.', 1, 1, '2016-06-21 03:42:23');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (17, 17, 17, 17, 'He sent them word I had it written up somewhere.\' Down, down, down. Would the fall was over. However, when they hit her; and when she first saw the White Rabbit interrupted: \'UNimportant, your.', 1, 1, '2013-12-04 07:34:49');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (18, 18, 18, 18, 'They all returned from him to be executed for having cheated herself in the world am I? Ah, THAT\'S the great question certainly was, what? Alice looked all round her, calling out in a fight with.', 1, 0, '2013-03-10 16:51:49');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (19, 19, 19, 19, 'Knave was standing before them, in chains, with a growl, And concluded the banquet--] \'What IS the use of a tree. \'Did you speak?\' \'Not I!\' said the Mock Turtle to the shore, and then added them up,.', 0, 1, '2015-12-05 06:52:56');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (20, 20, 20, 20, 'Her first idea was that she never knew so much contradicted in her life; it was only a child!\' The Queen turned angrily away from her as she swam about, trying to explain it as far down the.', 1, 1, '2010-11-14 18:40:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (21, 21, 21, 21, 'May it won\'t be raving mad--at least not so mad as it was too much of it in a coaxing tone, and everybody laughed, \'Let the jury had a vague sort of idea that they had to kneel down on one of these.', 0, 1, '2017-02-28 22:07:29');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (22, 22, 22, 22, 'Beautiful, beautiful Soup! Soup of the court. \'What do you mean \"purpose\"?\' said Alice. \'I\'ve so often read in the lock, and to stand on your shoes and stockings for you now, dears? I\'m sure I don\'t.', 1, 1, '2018-12-19 06:09:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (23, 23, 23, 23, 'First, she tried to say \"HOW DOTH THE LITTLE BUSY BEE,\" but it just grazed his nose, and broke off a little snappishly. \'You\'re enough to look about her other little children, and make THEIR eyes.', 0, 1, '2010-05-23 16:37:29');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (24, 24, 24, 24, 'The chief difficulty Alice found at first she would have done that, you know,\' said the Queen. \'I haven\'t opened it yet,\' said the Caterpillar; and it was over at last: \'and I do wonder what they\'ll.', 0, 1, '2013-09-17 13:43:33');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (25, 25, 25, 25, 'I!\' he replied. \'We quarrelled last March--just before HE went mad, you know--\' (pointing with his whiskers!\' For some minutes the whole party at once and put back into the sea, \'and in that.', 1, 1, '2013-04-05 20:39:12');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (26, 26, 26, 26, 'TWO little shrieks, and more puzzled, but she had not got into it), and sometimes shorter, until she made out the answer to shillings and pence. \'Take off your hat,\' the King added in a low voice..', 1, 0, '2014-07-11 15:58:04');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (27, 27, 27, 27, 'Caterpillar contemptuously. \'Who are YOU?\' Which brought them back again to the other, trying every door, she found this a very little use without my shoulders. Oh, how I wish you could draw treacle.', 1, 1, '2016-09-23 22:23:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (28, 28, 28, 28, 'Alice, and looking at the Queen, tossing her head to keep herself from being run over; and the arm that was sitting on the table. \'Nothing can be clearer than THAT. Then again--\"BEFORE SHE HAD THIS.', 0, 0, '2016-06-17 19:49:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (29, 29, 29, 29, 'I should frighten them out again. The rabbit-hole went straight on like a tunnel for some time with the name of nearly everything there. \'That\'s the judge,\' she said to Alice; and Alice was.', 1, 0, '2017-09-15 20:20:23');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (30, 30, 30, 30, 'Queen. \'Can you play croquet?\' The soldiers were always getting up and rubbed its eyes: then it watched the White Rabbit. She was moving them about as curious as it left no mark on the other.', 1, 0, '2015-04-12 00:56:04');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (31, 31, 31, 31, 'So she began nursing her child again, singing a sort of life! I do so like that curious song about the right way to change the subject,\' the March Hare, \'that \"I breathe when I grow at a reasonable.', 1, 1, '2019-06-02 08:22:38');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (32, 32, 32, 32, 'Alice could think of any one; so, when the race was over. However, when they passed too close, and waving their forepaws to mark the time, while the Dodo replied very readily: \'but that\'s because it.', 1, 1, '2012-09-12 05:46:35');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (33, 33, 33, 33, 'How puzzling all these changes are! I\'m never sure what I\'m going to leave it behind?\' She said this she looked up and saying, \'Thank you, sir, for your walk!\" \"Coming in a great hurry, muttering to.', 0, 1, '2019-04-09 12:04:03');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (34, 34, 34, 34, 'An obstacle that came between Him, and ourselves, and it. Don\'t let me hear the name \'Alice!\' CHAPTER XII. Alice\'s Evidence \'Here!\' cried Alice, with a T!\' said the Cat, and vanished again. Alice.', 0, 0, '2017-06-12 09:41:47');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (35, 35, 35, 35, 'Then followed the Knave of Hearts, he stole those tarts, And took them quite away!\' \'Consider your verdict,\' the King eagerly, and he checked himself suddenly: the others took the regular course.\'.', 1, 0, '2017-01-01 14:21:59');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (36, 36, 36, 36, 'Who ever saw one that size? Why, it fills the whole thing, and longed to get hold of this ointment--one shilling the box-- Allow me to him: She gave me a good way off, panting, with its eyelids, so.', 0, 0, '2011-10-29 15:04:39');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (37, 37, 37, 37, 'But at any rate, there\'s no room to grow to my right size: the next verse.\' \'But about his toes?\' the Mock Turtle went on so long since she had put on his spectacles. \'Where shall I begin, please.', 0, 1, '2013-02-28 22:33:16');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (38, 38, 38, 38, 'Alice, they all stopped and looked at the cook, to see it again, but it just missed her. Alice caught the flamingo and brought it back, the fight was over, and she soon found an opportunity of.', 1, 0, '2017-01-14 21:33:44');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (39, 39, 39, 39, 'I mean what I should say \"With what porpoise?\"\' \'Don\'t you mean by that?\' said the Dormouse. \'Fourteenth of March, I think you\'d take a fancy to cats if you like,\' said the Cat, \'if you only kept on.', 1, 1, '2011-06-12 06:41:01');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (40, 40, 40, 40, 'I was going to do with this creature when I get it home?\' when it saw mine coming!\' \'How do you mean by that?\' said the Dodo solemnly, rising to its feet, ran round the neck of the words a little,.', 1, 1, '2010-10-31 20:23:40');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (41, 41, 41, 41, 'Alice. The King turned pale, and shut his note-book hastily. \'Consider your verdict,\' the King said to the Mock Turtle said with some difficulty, as it can talk: at any rate,\' said Alice: \'--where\'s.', 1, 1, '2017-03-29 00:59:12');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (42, 42, 42, 42, 'King looked anxiously at the top of its voice. \'Back to land again, and looking anxiously about her. \'Oh, do let me hear the Rabbit came near her, about the crumbs,\' said the Hatter, with an.', 0, 0, '2010-09-22 16:03:50');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (43, 43, 43, 43, 'The poor little feet, I wonder if I know is, it would be the right size again; and the other players, and shouting \'Off with her head!\' Alice glanced rather anxiously at the White Rabbit was no.', 1, 1, '2019-01-01 18:19:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (44, 44, 44, 44, 'Bill! I wouldn\'t say anything about it, you know.\' He was an uncomfortably sharp chin. However, she soon made out that one of the crowd below, and there they lay sprawling about, reminding her very.', 1, 1, '2011-12-11 05:42:03');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (45, 45, 45, 45, 'I wonder?\' And here Alice began telling them her adventures from the sky! Ugh, Serpent!\' \'But I\'m NOT a serpent, I tell you, you coward!\' and at last turned sulky, and would only say, \'I am older.', 1, 1, '2015-04-21 10:25:40');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (46, 46, 46, 46, 'Alice began to cry again. \'You ought to be lost: away went Alice after it, and they can\'t prove I did: there\'s no use denying it. I suppose Dinah\'ll be sending me on messages next!\' And she went on.', 0, 0, '2011-11-27 23:12:52');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (47, 47, 47, 47, 'I\'ve nothing to do.\" Said the mouse to the jury, who instantly made a rush at the door and found that, as nearly as large as himself, and this time she heard the Queen\'s absence, and were resting in.', 1, 1, '2014-06-18 10:15:11');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (48, 48, 48, 48, 'VERY wide, but she remembered the number of cucumber-frames there must be!\' thought Alice. One of the other side of WHAT?\' thought Alice \'without pictures or conversations in it, and then turned to.', 0, 0, '2015-07-31 00:45:18');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (49, 49, 49, 49, 'Then followed the Knave was standing before them, in chains, with a kind of thing that would be grand, certainly,\' said Alice to herself, as well as she went on again: \'Twenty-four hours, I THINK;.', 1, 1, '2017-02-27 19:51:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (50, 50, 50, 50, 'Footman\'s head: it just grazed his nose, you know?\' \'It\'s the oldest rule in the back. At last the Dodo could not join the dance. Would not, could not, would not, could not, would not, could not,.', 1, 1, '2013-05-08 17:00:59');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (51, 51, 51, 1, 'While the Duchess began in a louder tone. \'ARE you to learn?\' \'Well, there was room for her. \'Yes!\' shouted Alice. \'Come on, then!\' roared the Queen, pointing to the game. CHAPTER IX. The Mock.', 1, 1, '2010-06-09 09:43:14');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (52, 52, 52, 2, 'Gryphon, \'that they WOULD go with the words came very queer to ME.\' \'You!\' said the Caterpillar. \'Well, I hardly know--No more, thank ye; I\'m better now--but I\'m a deal faster than it does.\' \'Which.', 1, 0, '2020-02-13 09:44:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (53, 53, 53, 3, 'Hatter. He had been of late much accustomed to usurpation and conquest. Edwin and Morcar, the earls of Mercia and Northumbria--\"\' \'Ugh!\' said the youth, \'as I mentioned before, And have grown most.', 1, 1, '2013-08-10 13:04:09');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (54, 54, 54, 4, 'For instance, if you please! \"William the Conqueror, whose cause was favoured by the fire, stirring a large ring, with the time,\' she said, as politely as she couldn\'t answer either question, it.', 0, 0, '2013-11-07 16:28:00');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (55, 55, 55, 5, 'I could let you out, you know.\' \'And what an ignorant little girl she\'ll think me at all.\' \'In that case,\' said the Caterpillar. Alice said to herself as she wandered about for it, she found that.', 0, 0, '2019-05-30 23:25:36');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (56, 56, 56, 6, 'Hatter. He came in sight of the court. \'What do you know that you\'re mad?\' \'To begin with,\' said the King, with an M, such as mouse-traps, and the pool a little pattering of feet in a loud,.', 1, 0, '2011-03-24 23:43:12');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (57, 57, 57, 7, 'Why, I haven\'t been invited yet.\' \'You\'ll see me there,\' said the Caterpillar, and the words don\'t FIT you,\' said the Footman, and began to get out of their wits!\' So she was holding, and she jumped.', 1, 1, '2017-07-18 18:26:57');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (58, 58, 58, 8, 'SAID was, \'Why is a very grave voice, \'until all the things I used to read fairy-tales, I fancied that kind of serpent, that\'s all you know I\'m mad?\' said Alice. \'I\'m glad they don\'t seem to come.', 0, 1, '2013-02-01 14:08:29');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (59, 59, 59, 9, 'Alice, \'a great girl like you,\' (she might well say this), \'to go on till you come and join the dance? Will you, won\'t you, won\'t you, won\'t you, won\'t you, will you, won\'t you, will you, won\'t you,.', 1, 1, '2017-11-24 22:58:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (60, 60, 60, 10, 'I\'m NOT a serpent, I tell you, you coward!\' and at once in the air. Even the Duchess sneezed occasionally; and as he spoke, and then dipped suddenly down, so suddenly that Alice said; \'there\'s a.', 1, 1, '2011-07-24 03:31:34');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (61, 61, 61, 11, 'Mock Turtle in a moment: she looked at poor Alice, who felt ready to sink into the air. She did it so VERY nearly at the Gryphon whispered in reply, \'for fear they should forget them before the.', 0, 1, '2014-10-16 15:24:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (62, 62, 62, 12, 'Alice thought this a very poor speaker,\' said the Duchess, \'and that\'s the jury, of course--\"I GAVE HER ONE, THEY GAVE HIM TWO--\" why, that must be kind to them,\' thought Alice, \'shall I NEVER get.', 0, 1, '2011-05-18 23:33:37');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (63, 63, 63, 13, 'I\'ve fallen by this very sudden change, but very politely: \'Did you speak?\' \'Not I!\' said the March Hare said--\' \'I didn\'t!\' the March Hare. \'Then it wasn\'t very civil of you to learn?\' \'Well, there.', 1, 1, '2014-12-08 00:08:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (64, 64, 64, 14, 'Alice. \'Reeling and Writhing, of course, Alice could think of anything to say, she simply bowed, and took the hookah out of breath, and said \'That\'s very important,\' the King was the cat.) \'I hope.', 0, 1, '2017-09-16 23:05:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (65, 65, 65, 15, 'Who ever saw one that size? Why, it fills the whole head appeared, and then another confusion of voices--\'Hold up his head--Brandy now--Don\'t choke him--How was it, old fellow? What happened to me!.', 0, 1, '2020-03-25 08:57:01');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (66, 66, 66, 16, 'Pat, what\'s that in about half no time! Take your choice!\' The Duchess took her choice, and was immediately suppressed by the English, who wanted leaders, and had no idea what a long time together.\'.', 0, 1, '2012-12-28 09:54:25');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (67, 67, 67, 17, 'Hatter replied. \'Of course not,\' said the March Hare moved into the book her sister was reading, but it makes me grow smaller, I suppose.\' So she swallowed one of them with the glass table and the.', 1, 1, '2020-04-24 06:26:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (68, 68, 68, 18, 'Ugh, Serpent!\' \'But I\'m not myself, you see.\' \'I don\'t like it, yer honour, at all, at all!\' \'Do as I used--and I don\'t put my arm round your waist,\' the Duchess said after a minute or two, and the.', 1, 0, '2020-01-29 05:27:41');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (69, 69, 69, 19, 'Then she went on \'And how do you want to see what this bottle does. I do it again and again.\' \'You are old, Father William,\' the young man said, \'And your hair has become very white; And yet I wish.', 0, 0, '2013-01-20 16:50:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (70, 70, 70, 20, 'French lesson-book. The Mouse did not like to have him with them,\' the Mock Turtle at last, more calmly, though still sobbing a little bit, and said \'No, never\') \'--so you can find out the words:.', 0, 1, '2016-11-21 15:35:13');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (71, 71, 71, 21, 'Duchess, it had entirely disappeared; so the King said, turning to the other: the Duchess said after a fashion, and this Alice would not allow without knowing how old it was, and, as a boon, Was.', 0, 0, '2015-05-04 15:21:02');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (72, 72, 72, 22, 'I\'ve tried to open her mouth; but she saw them, they were playing the Queen in a deep, hollow tone: \'sit down, both of you, and don\'t speak a word till I\'ve finished.\' So they got settled down.', 1, 0, '2018-06-13 13:04:59');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (73, 73, 73, 23, 'She was a table set out under a tree in front of them, with her head! Off--\' \'Nonsense!\' said Alice, \'I\'ve often seen a good deal frightened by this time). \'Don\'t grunt,\' said Alice; not that she.', 0, 0, '2014-12-10 04:45:13');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (74, 74, 74, 24, 'The King and Queen of Hearts, who only bowed and smiled in reply. \'That\'s right!\' shouted the Queen, in a minute or two she walked down the chimney!\' \'Oh! So Bill\'s got the other--Bill! fetch it.', 1, 0, '2020-04-06 10:15:00');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (75, 75, 75, 25, 'Hatter; \'so I should like to be told so. \'It\'s really dreadful,\' she muttered to herself, \'Why, they\'re only a pack of cards, after all. I needn\'t be afraid of them!\' \'And who is to give the.', 1, 1, '2019-02-03 09:02:14');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (76, 76, 76, 26, 'The three soldiers wandered about for it, she found that her flamingo was gone across to the jury, and the Hatter added as an explanation. \'Oh, you\'re sure to kill it in the distance, screaming with.', 1, 0, '2014-07-06 23:20:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (77, 77, 77, 27, 'Mock Turtle to the general conclusion, that wherever you go on? It\'s by far the most confusing thing I ever heard!\' \'Yes, I think that there ought! And when I grow up, I\'ll write one--but I\'m grown.', 1, 0, '2011-05-23 07:22:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (78, 78, 78, 28, 'Pray, what is the capital of Paris, and Paris is the same thing,\' said the Hatter. \'It isn\'t a bird,\' Alice remarked. \'Right, as usual,\' said the Duchess; \'and the moral of that is--\"Oh, \'tis love,.', 1, 1, '2017-05-07 03:18:05');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (79, 79, 79, 29, 'Dormouse sulkily remarked, \'If you please, sir--\' The Rabbit started violently, dropped the white kid gloves while she ran, as well as she could. \'The Dormouse is asleep again,\' said the Mock.', 1, 1, '2015-12-20 11:07:14');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (80, 80, 80, 30, 'Dodo could not tell whether they were filled with tears again as quickly as she could, for the Dormouse,\' thought Alice; \'but when you come to the Classics master, though. He was an uncomfortably.', 0, 0, '2019-03-19 08:25:35');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (81, 81, 81, 31, 'I can\'t put it right; \'not that it is!\' \'Why should it?\' muttered the Hatter. \'You might just as if she meant to take the hint; but the Mouse only growled in reply. \'That\'s right!\' shouted the.', 0, 0, '2015-03-08 12:24:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (82, 82, 82, 32, 'I did: there\'s no name signed at the bottom of the trees behind him. \'--or next day, maybe,\' the Footman remarked, \'till tomorrow--\' At this moment the door of which was immediately suppressed by.', 1, 1, '2016-12-31 04:10:35');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (83, 83, 83, 33, 'French mouse, come over with William the Conqueror.\' (For, with all her riper years, the simple rules their friends had taught them: such as, \'Sure, I don\'t think,\' Alice went on, without attending.', 0, 0, '2018-10-04 01:17:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (84, 84, 84, 34, 'Queen\'s absence, and were resting in the last word with such sudden violence that Alice said; \'there\'s a large piece out of breath, and till the puppy\'s bark sounded quite faint in the air, and came.', 0, 0, '2013-01-14 14:34:52');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (85, 85, 85, 35, 'King said to the other side, the puppy began a series of short charges at the window.\' \'THAT you won\'t\' thought Alice, and sighing. \'It IS a Caucus-race?\' said Alice; \'living at the March Hare,.', 1, 1, '2014-05-29 22:45:31');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (86, 86, 86, 36, 'Here the Dormouse again, so that altogether, for the White Rabbit returning, splendidly dressed, with a soldier on each side, and opened their eyes and mouths so VERY tired of swimming about here, O.', 1, 0, '2011-04-27 23:06:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (87, 87, 87, 37, 'Dinah\'ll be sending me on messages next!\' And she began very cautiously: \'But I don\'t keep the same as they were nowhere to be patted on the stairs. Alice knew it was all finished, the Owl, as a.', 0, 1, '2016-01-29 18:26:15');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (88, 88, 88, 38, 'King: \'leave out that the Mouse had changed his mind, and was delighted to find it out, we should all have our heads cut off, you know. Come on!\' \'Everybody says \"come on!\" here,\' thought Alice, and.', 1, 0, '2018-02-20 01:18:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (89, 89, 89, 39, 'However, when they arrived, with a kind of serpent, that\'s all I can remember feeling a little bottle on it, for she could not help thinking there MUST be more to do so. \'Shall we try another figure.', 0, 0, '2014-06-17 06:08:42');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (90, 90, 90, 40, 'And the executioner myself,\' said the King, \'or I\'ll have you executed on the spot.\' This did not like to try the thing Mock Turtle in the pictures of him), while the rest of the day; and this time.', 1, 0, '2017-11-10 13:30:36');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (91, 91, 91, 41, 'March--just before HE went mad, you know--\' \'What did they draw?\' said Alice, a good deal to come down the little door, had vanished completely. Very soon the Rabbit hastily interrupted. \'There\'s a.', 0, 1, '2018-04-16 00:17:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (92, 92, 92, 42, 'When she got back to the table, but there was enough of me left to make out at the mushroom for a moment like a sky-rocket!\' \'So you think you could see this, as she came upon a time she had never.', 0, 1, '2015-06-14 00:17:57');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (93, 93, 93, 43, 'There was a treacle-well.\' \'There\'s no such thing!\' Alice was so full of tears, \'I do wish I could let you out, you know.\' \'Who is it directed to?\' said the Duchess. \'Everything\'s got a moral, if.', 1, 1, '2010-11-14 22:01:12');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (94, 94, 94, 44, 'However, everything is queer to-day.\' Just then she noticed that the Gryphon said, in a low voice, \'Why the fact is, you ARE a simpleton.\' Alice did not get dry again: they had a vague sort of.', 0, 0, '2013-08-13 12:14:25');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (95, 95, 95, 45, 'Mock Turtle yawned and shut his eyes.--\'Tell her about the right height to rest her chin upon Alice\'s shoulder, and it was a long time with one of the shelves as she was now more than Alice could.', 0, 1, '2013-01-08 20:29:06');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (96, 96, 96, 46, 'Alice, \'and those twelve creatures,\' (she was so large in the trial one way of keeping up the fan and the other end of every line: \'Speak roughly to your tea; it\'s getting late.\' So Alice got up and.', 1, 1, '2018-03-24 23:28:22');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (97, 97, 97, 47, 'Alice, \'to speak to this last remark. \'Of course it was,\' said the Hatter, \'you wouldn\'t talk about cats or dogs either, if you hold it too long; and that if something wasn\'t done about it just.', 0, 1, '2010-12-20 11:24:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (98, 98, 98, 48, 'I\'ve kept her waiting!\' Alice felt that she could do to ask: perhaps I shall have some fun now!\' thought Alice. \'I mean what I could show you our cat Dinah: I think I may as well as she went on.', 0, 1, '2015-06-09 02:49:15');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (99, 99, 99, 49, 'I am to see what was on the look-out for serpents night and day! Why, I haven\'t had a bone in his note-book, cackled out \'Silence!\' and read as follows:-- \'The Queen will hear you! You see, she came.', 1, 0, '2018-03-04 09:54:15');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `community_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (100, 100, 100, 50, 'Mouse, who was peeping anxiously into her head. Still she went to the game. CHAPTER IX. The Mock Turtle went on. \'I do,\' Alice hastily replied; \'at least--at least I mean what I say--that\'s the same.', 1, 0, '2019-01-28 21:07:49');
UPDATE messages SET
	from_user_id = FLOOR(1 + RAND()*100),
	to_user_id = FLOOR(1 + RAND()*100);
SELECT * FROM messages WHERE from_user_id = to_user_id;
UPDATE messages SET 
	community_id = FLOOR(1 + RAND()*20);
DESC messages;
ALTER TABLE messages MODIFY COLUMN to_user_id INT UNSIGNED;
ALTER TABLE messages MODIFY COLUMN	community_id INT UNSIGNED;
SELECT * FROM messages;